version: "3"
services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ./:/app
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespass
volumes:
  db_data: {}
